### ISSUE TITLE
Reproducible bug in ExtractConstant

### ISSUE THREAD

**Issue by nrocy** [ecomba/vim-ruby-refactoring#12]
Steps to reproduce:

http://gist.github.com/646146

**Comment by ecomba** [comment]
The problem here seems to be that the ExtractConstant function finds "empty_array.class" in line 8 and thinks that that is the name of the class!

Well spotted!

**Comment by ecomba** [comment]
Modified the finder function (exec "?\<class\\|module\\>") to find at the beginning of the line for the moment (exec "?^\<class\\|module\\>").

Cheers!
